/*
 * NewAbout.java
 *
 * Created on November 27, 2004, 4:50 PM
 */package com.developingstorm.games.sad.ui;

/**
 * 
 * @author Owner
 */
public class NewAbout extends javax.swing.JDialog {

  /** Creates new form NewAbout */
  public NewAbout(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  private void initComponents() {// GEN-BEGIN:initComponents

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    pack();
  }// GEN-END:initComponents

  /**
   * @param args
   *          the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new NewAbout(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}
